spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      # 존재하지 않는 테이블/제약조건 삭제 시 에러 무시
      jdbc:
        # MySQL에서 IF EXISTS 조건 자동 추가
        globally_quoted_identifiers: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

kopis:
  api:
    key: ${KOPIS_API_KEY}
    url: ${KOPIS_API_URL}

